[profile.default]
src = 'src'
test = 'test'
out = 'artifacts'
libs = ['lib']
solc_version = '0.8.16'
extra_output = [
  "abi",
  "evm.bytecode",
  "evm.deployedBytecode",
  "evm.methodIdentifiers",
]
optimizer = true
optimizer_runs = 20_000
force = false
# See more config options https://github.com/foundry-rs/foundry/tree/master/conf