name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        # with:
        # submodules: "recursive" # Ensures submodules are checked out

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: |
          sudo apt -y update && sudo apt -y install libusb-1.0-0-dev libudev-dev
          yarn install

      - name: Setup Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup Env
        env:
          INFURA_ID: ${{ secrets.INFURA_ID }}
          API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
        run: |
          echo "INFURA_ID=$INFURA_ID" > ./packages/dapp/.env
          echo "API_KEY_ALCHEMY=$API_KEY_ALCHEMY" >> ./packages/dapp/.env
      - name: Forge Install
        run: yarn workspace @ubiquity/contracts forge install

      - name: Build
        run: |
          yarn
          yarn build:all

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: static
          path: packages/dapp/dist
