name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - development
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update Diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
          output_file: "utils/diagram.svg"
          root_path: "packages/"
          commit_message: "ci: update diagram"