name: Received PR and Deploy

on:
  workflow_run:
    workflows: ["Install and Build Workflow for Pull Request"]
    types:
      - completed

jobs:
  receive-pr-and-deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Download artifact"
        uses: actions/github-script@v3.1.0
        with:
          script: |
            const run_id = ${{ github.event.workflow_run.id }};
            const downloadArtifact = require('./download-artifact.js')(github, context, run_id);
      - name: Extract files
        run: |
          unzip pr.zip
          unzip pull-request.zip
          ls

      - name: Deploy Development
        run: |
          netlify link --id ${{ secrets.NETLIFY_SITE_ID_DEVELOPMENT }}
          netlify deploy --prod > ./deployments.log

      - name: "Comment on PR"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: require('./comment-on-pr.js')(github, context);
