name: Test deploy

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Test deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Test deploy
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");
            const print_deployments_log = require('${{ github.workspace }}/utils/print_deployments_logs.js');
            
            async function run() {
              const { context } = github;
              const { payload } = context;
            
              if (context.eventName === 'pull_request') {
                const pullRequestNumber = payload.pull_request.number;
                console.log(`Pull Request Number: ${pullRequestNumber}`);
                // Pass pullRequestNumber to your print_deployments_log function
                await print_deployments_log({ github, context, fs, pullRequestNumber });
              }
            }
            
            run();
