name: Install and run Yarn Audit

on:
  pull_request:
  push:
  create:
    tag:
      - "v*"

jobs:
  build-and-audit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Yarn
        run: yarn install

      - name: Install Yarn Audit Package
        run: yarn add yarn-audit-fix -D

      - name: Audit and Attempt Fix
        run: yarn run yarn-audit-fix
