name: Yarn Audit

on:
  workflow_run:
    workflows: ["Receive Workflow and Deploy"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Yarn Audit
        uses: pragatheeswarans/yarn-audit-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          assignee: 'ubiquity-dollar'
          label: 'audit issues'
          title: 'Yarn Audit Security Issue'
          description: 'There are some high priority issues with your packages. Please check them.'
          paths: |
            ../
            ../packages/contracts
            ../packages/dapp


