name: Yarn Audit

on: 
  push: 
  fork: 
  pull_requests:

jobs:
  yarn-audit-and-fix:
  runs-on: ubuntu-22.04
  steps:
    - uses: actions/checkout@v2

    - run:
      name: "Run yarn audit"
      command: |
        set +e
        yarn audit 2>yarn-audit-errors
        result=$?
        set -e

        function check-for-down-server() {
          if grep -q "Error: Request failed" yarn-audit-errors; then
            cat yarn-audit-errors
            echo
            echo "NPM's audit servers are down."
            echo This happen so often that we are going to ignore this and
            echo assume everything is okay.
            exit 0
          fi
        }
        if [ "$result" != 0 ]; then
          check-for-down-server
          if [ -f yarn-audit-known-issues ]; then
            set +e
            yarn audit --json 2>yarn-audit-errors | grep auditAdvisory > yarn-audit-issues
            set -e
            check-for-down-server
            if diff -q yarn-audit-known-issues yarn-audit-issues > /dev/null 2>&1; then
              echo
              echo Ignorning known vulnerabilities
              exit 0
            fi
          fi
          echo
          echo Security vulnerabilities were found that were not ignored
          echo
          echo Check to see if these vulnerabilities apply to production
          echo and/or if they have fixes available. If they do not have
          echo fixes and they do not apply to production, you may ignore them
          echo
          echo To ignore these vulnerabilities, run:
          echo
          echo "yarn audit --json | grep auditAdvisory > yarn-audit-known-issues"
          echo
          echo and commit the yarn-audit-known-issues file
          exit "$result"
        fi
